# Generated by Django 4.2.16 on 2025-09-13 07:03

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('salary', models.FloatField()),
                ('joining_date', models.DateField()),
                ('skills', djongo.models.fields.JSONField()),
            ],
        ),
    ]
